### ISSUE TITLE
configured port is not used when connecting to database

### ISSUE THREAD

**Issue by mavolkmer** [sourcebroker/deployer-extended-database#15]
With the possibility to configure the db-port, which is already used in https://github.com/sourcebroker/deployer-extended-database/blob/0d9ac121a087233ee2c08832ff41b2acf29a34d5/deployer/db/task/db_export.php#L42 one gets confused when the already set port is not used with mysqli_connect.

I've prepared a PR to use this parameter also in 'DatabaseUtility' - see https://github.com/sourcebroker/deployer-extended-database/pull/14

**Comment by kszymukowicz** [comment]
Tnx!
