### ISSUE TITLE
Add mysqli flags (e. g. for SSL database connections)

### ISSUE THREAD

**Issue by JulianXIMA** [sourcebroker/deployer-extended-database#21]
Currently there is only "host", "user", "password", "dbname" and "port" possible to establish a db-connection (e. g. for db:truncate, db:export, ...). Right now it is not possible to use mysql flags or certificates parameters to use ssl.

It would be nice to implement that in DatabaseUtility.php and the affected deployer-tasks of deployer-extended-database.

To use flags (e. g. for SSL) it also needs to be switched from "mysqli_connect" to "mysqli_real_connect" (https://www.php.net/manual/en/mysqli.real-connect.php). 

This change would also need to expand the variable `set('db_databases',...`. Right?

**Comment by kszymukowicz** [comment]
@maikschneider Tnx for the PR!

**Comment by kszymukowicz** [comment]
@JulianXIMA can you somehow test dev-master if it works for your needs?

**Comment by JulianXIMA** [comment]
@kszymukowicz works for me. Thanks!
