### ISSUE TITLE
"There are no commands defined in the "db" namespace." error

### ISSUE THREAD

**Issue by tmsss** [sourcebroker/deployer-extended-database#5]
Hi there, I'm running deployer on windows 10 via composer and the rest of the deployer tasks work, but when I call any database command I get the following error:
`
There are no commands defined in the "db" namespace.`

I presume the deployer script isn't loading properly the deployer extended database files but I cannot fix it, can you help me here?

Thanks!

**Comment by tmsss** [comment]
Just an update, I'm checking the vendor folder and somehow the deployer/db/task folder is empty. I tried to clone the repo directly and it stays that way.

**Comment by kszymukowicz** [comment]
I suppose problem is that Windows does not support ":" in filename.
I will fix that in next major release.

**Comment by tmsss** [comment]
Thank you for the response and for all your work! I run other commands with ':' and they work, like deploy:unlock as example. Meanwhile, I've downloaded your bux fix branch, but now I'm getting:

`[Error] Call to undefined function Deployer\server()`

**Comment by kszymukowicz** [comment]
You can create cli commands with ":" but the files that store the task can not have ":" in filename.
Version 9.0.0 has no filenames with ":" and its Deployer 6 compatible. 

Anyway I did not tested it with Windows at all.
